### ISSUE TITLE
Problem to show accented characters.

### ISSUE THREAD

**Issue by djamalseck** [creativetimofficial/now-ui-kit-angular#1]
I create a test component:
      ng g component components/test
<br>I write in the template file components/test.component.html the following french sentence:  
        L'élève va à l'école.

But, in the browser, I get the result :
L'�l�ve va � l'�cole.

**Comment by chelaruc** [comment]
Hi, @djamalseck! What browser do you use? Best, Ciprian

**Comment by djamalseck** [comment]
Hello.

Thank you for your quick response.
I use Micosoft Edge.
Note that I tried Paper Kit 2 Angular also but didn't encounter this problem.

Best regards,
Djamal.
________________________________
De : Chelaru Ciprian <notifications@github.com>
Envoyé : lundi 14 mai 2018 09:00
À : creativetimofficial/now-ui-kit-angular
Cc : djamalseck; Mention
Objet : Re: [creativetimofficial/now-ui-kit-angular] Problem to show accented characters. (#1)


Hi, @djamalseck<https://github.com/djamalseck>! What browser do you use? Best, Ciprian

**Comment by djamalseck** [comment]
Hello.
Thank you for your advice. Indeed, my problem has been solved after I changed the editor (from visual studio 2017 to visual studio code). After that, I had only to corect the text in the template. That was a problem of encoding.
Best regards.
Djamal.
________________________________
De : Chelaru Ciprian <notifications@github.com>
Envoyé : mercredi 16 mai 2018 09:04
À : creativetimofficial/now-ui-kit-angular
Cc : djamalseck; Mention
Objet : Re: [creativetimofficial/now-ui-kit-angular] Problem to show accented characters. (#1)


@djamalseck<https://github.com/djamalseck> Can you try another editor?
